language: node_js
node_js:
  - "12"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint && yarn test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
