service: okta-hooks

provider:
  name: aws
  stage: ${env:ENVIRONMENT}
  runtime: nodejs12.x
  region: us-east-1
  vpc:
    securityGroupIds:
      - ${file(${env:ECS_CONFIG}/bin/vars.yml):us-east-1.webapp_elb_sg}
    subnetIds: ${file(${env:ECS_CONFIG}/bin/vars.yml):us-east-1.prod_apps_1_all}
  stackTags:
    Name: ${env:PROJECT_NAME}-${self:custom.environmentMap.${env:ENVIRONMENT}}
    owner: devops-engineering-team@cru.org
    application: ${env:PROJECT_NAME}
    env: ${self:custom.environmentMap.${env:ENVIRONMENT}}
    managed_by: serverless-framework
    function: lambda
  iamRoleStatements:
    - Effect: Allow
      Action:
        - SNS:Publish
        - SNS:Subscribe
      Resource:
        Ref: OktaEventsSNSTopic
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - Fn::GetAtt: [ OktaRestrictedDomainsTable, Arn ]
  environment: ${file(serverless/environment.js)}

package:
  individually: true
  exclude:
    - .serverless/**
    - .webpack/**
    - .git/**
    - test/**
    - '**/*.test.js'
    - '**/*.sql'
    - .deployment/**

plugins:
  - '@cruglobal/serverless-merge-config'
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
    excludeFiles: '**/*.test.js'
  environmentMap:
    production: prod
    staging: stage
    development: dev
    lab: lab

resources:
  Resources:
    IamRoleLambdaExecution:
      Properties:
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
          - arn:aws:iam::aws:policy/service-role/AWSLambdaENIManagementAccess

    OktaLoadBalancer:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        Name: okta-hooks-${env:ENVIRONMENT}-alb
        Type: application
        Scheme: internet-facing
        IpAddressType: ipv4
        SecurityGroups:
          - ${file(${env:ECS_CONFIG}/bin/vars.yml):us-east-1.webapp_elb_sg}
        Subnets: ${file(${env:ECS_CONFIG}/bin/vars.yml):us-east-1.prod_public_1_all}
        LoadBalancerAttributes:
          - Key: access_logs.s3.enabled
            Value: true
          - Key: access_logs.s3.bucket
            Value: cru-alb-logs
          - Key: access_logs.s3.prefix
            Value: okta-hooks/${env:ENVIRONMENT}

    OktaLoadBalancerListener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        LoadBalancerArn:
          Ref: OktaLoadBalancer
        Certificates:
          - CertificateArn: ${file(${env:ECS_CONFIG}/bin/vars.yml):us-east-1.cru_wildcard_ssl}
        DefaultActions:
          - Type: fixed-response
            Order: 1
            FixedResponseConfig:
              StatusCode: 403
              ContentType: application/json
              MessageBody: '{"error": "Forbidden"}'
        Port: 443
        Protocol: HTTPS

    VerificationAlbListenerRule2:
      Properties:
        # serverless framework only allows a single header condition, we handle all verification conditions here
        Conditions:
          - Field: path-pattern
            Values:
              - /events
          - Field: http-request-method
            HttpRequestMethodConfig:
              Values:
                - GET
          - Field: http-header
            HttpHeaderConfig:
              HttpHeaderName: Authorization
              Values:
                - ${env:OKTA_SHARED_SECRET}
          - Field: http-header
            HttpHeaderConfig:
              HttpHeaderName: X-Okta-Verification-Challenge
              Values:
                - ?*

    OktaEventsSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Okta Events
        TopicName: ${self:service}-${env:ENVIRONMENT}-lifecycle-events

    OktaRestrictedDomainsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${env:ENVIRONMENT}-restricted-domains
        AttributeDefinitions:
          - AttributeName: DomainName
            AttributeType: S
        KeySchema:
          - AttributeName: DomainName
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  registration:
    handler: hooks/inline/registration.handler
    memorySize: 128
    timeout: 5
    description: Registration hook to generate a new GUID and prevent signup with restricted domain.
    environment:
      DYNAMODB_RESTRICTED_DOMAINS:
        Ref: OktaRestrictedDomainsTable
    events:
      - alb:
          listenerArn:
            Ref: OktaLoadBalancerListener
          priority: 1
          conditions:
            header:
              name: Authorization
              values:
                - ${env:OKTA_SHARED_SECRET}
            method:
              - POST
            path: /registration

  verification:
    handler: hooks/event/verification.handler
    memorySize: 128
    timeout: 5
    description: Event hook Verification
    events:
      - alb:
          listenerArn:
            Ref: OktaLoadBalancerListener
          priority: 2
          conditions: {} # conditions are handled in Resources block for verification lambda

  events:
    handler: hooks/event/events.handler
    memorySize: 128
    timeout: 5
    description: Event hook for all okta events
    environment:
      SNS_OKTA_EVENTS_ARN:
        Ref: OktaEventsSNSTopic
    events:
      - alb:
          listenerArn:
            Ref: OktaLoadBalancerListener
          priority: 3
          conditions:
            header:
              name: Authorization
              values:
                - ${env:OKTA_SHARED_SECRET}
            method:
              - POST
            path: /events

  userLifecycleCreate:
    handler: sns/user/lifecycle/create.handler
    description: Handle all `user.lifecycle.create` okta events
    memorySize: 256
    timeout: 12
    events:
      - sns:
          arn: !Ref OktaEventsSNSTopic
          topicName: ${self:service}-${env:ENVIRONMENT}-lifecycle-events
          filterPolicy:
            eventType:
              - user.lifecycle.create

  userLifecycleStatusChange:
    handler: sns/user/lifecycle/status-change.handler
    description: Handles all `user.lifecycle.deactivated` and `user.lifecycle.reactivate` okta events
    memorySize: 128
    timeout: 6
    events:
      - sns:
          arn: !Ref OktaEventsSNSTopic
          topicName: ${self:service}-${env:ENVIRONMENT}-lifecycle-events
          filterPolicy:
            eventType:
              - user.lifecycle.deactivate
              - user.lifecycle.reactivate

  userAccountUpdateProfile:
    handler: sns/user/account/update-profile.handler
    description: Handle all `user.account.update_profile` okta events
    memorySize: 256
    timeout: 12
    events:
      - sns:
          arn: !Ref OktaEventsSNSTopic
          topicName: ${self:service}-${env:ENVIRONMENT}-lifecycle-events
          filterPolicy:
            eventType:
              - user.account.update_profile

  syncRestrictedDomains:
    handler: schedule/sync-restricted-domains.handler
    description: Sync list of restricted domains from Google Sheet
    memorySize: 1024
    timeout: 120
    environment:
      DYNAMODB_RESTRICTED_DOMAINS:
        Ref: OktaRestrictedDomainsTable
    events:
      # Run daily at 12:00a and 12:00p UTC
      - schedule: cron(0 0,12 * * ? *)

  syncMissingOktaUsers:
    handler: schedule/sync-missing-okta-users.handler
    description: Query okta users missing Global Registry IDs and enqueue to SNS to re-sync them.
    memorySize: 1024
    timeout: 120
    environment:
      SNS_OKTA_EVENTS_ARN:
        Ref: OktaEventsSNSTopic
    events:
      # Run every 30 minutes.
      - schedule: cron(0/30 * * * ? *)
