name: Deploy Serverless Functions

on:
  push:
    branches:
      # Automatically build and deploy master and staging. Additional branches may be added.
      - master
      - staging
      - gha-deploy-serverless
  workflow_dispatch:
    # Allows manual build and deploy of any branch/ref

jobs:
  # Deploy Serverless functions
  deploy:
    name: Deploy
    uses: CruGlobal/.github/.github/workflows/deploy-serverless.yml@serverless
    with:
      workflow-ref: serverless
